### ISSUE TITLE
Add the possibility to store the robot name inside the telemetry

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/robometry#160]
It would be nice to add a string containing the name of the robot.
The idea is to add it at the same level of `description_list` a possible name could be `robot_name`.

What do you think @Nicogene @S-Dafarra @traversaro @AlexAntn

**Comment by Nicogene** [comment]
I think it can be added without problems!

**Comment by S-Dafarra** [comment]
I think it is ok to add it. Do you envision cases where different signals have different ``robot_name``s?

On a more abstract level, I think this issue is a close relative to https://github.com/robotology/yarp-telemetry/issues/156

In general, I think that these issues could be solved in the long-term by adding some sort of custom configuration struct (like in https://github.com/robotology/yarp-telemetry/issues/154)

**Comment by traversaro** [comment]
Probably we can be explicit and call it `yarp_robot_name` ? Just to avoid problems if in the future we want to encode other robot-related information (such as directly URI of the URDF model using the ROS-URI `package://robots/iCubGenova09/model.urdf`, see https://github.com/robotology/icub-models/issues/90) and we may get confused.

**Comment by GiulioRomualdi** [comment]
I will go for yarp_robot_name!

**Comment by GiulioRomualdi** [comment]
> I think it is ok to add it. Do you envision cases where different signals have different robot_names?

For the time being, I would just add a string that should contain the `yarp_robot_name` of the machine where the yarp_telemetry is used.
Then I agree we should add a struct containing several info. i.e. the robot name, the text logs (the one displayed in `YarpLog` for each IP)
